"""Add constraints, soft deletes, and indexing

Revision ID: 2c547a27ae96
Revises: 3d9fcadf6af0
Create Date: 2026-01-03 07:06:34.537197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c547a27ae96'
down_revision: Union[str, Sequence[str], None] = '3d9fcadf6af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_group_uc', 'groups', ['name', 'user_id'])
    op.alter_column('tasks', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('_user_task_group_uc', 'tasks', ['title', 'group_id', 'user_id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('_user_task_group_uc', 'tasks', type_='unique')
    op.alter_column('tasks', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('_user_group_uc', 'groups', type_='unique')
    # ### end Alembic commands ###
