"""Add constraints, soft deletes, and indexing

Revision ID: 3d9fcadf6af0
Revises: 761b543df782
Create Date: 2026-01-03 06:47:26.432351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9fcadf6af0'
down_revision: Union[str, Sequence[str], None] = '761b543df782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('groups', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tasks_is_completed'), 'tasks', ['is_completed'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_completed'), table_name='tasks')
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tasks', 'deleted_at')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.alter_column('groups', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('groups', 'deleted_at')
    # ### end Alembic commands ###
